### PR TITLE
Merge/sound upstream 20240122

### PR DESCRIPTION
**Pull request by ujfalusi**
Hi,

first 6.8-rc1 attempt.

Replaces #4778

### CODE REVIEW

**Comment by ujfalusi** [comment]
Gash, another release, another `deb-pkg` change to break CI?

**Comment by ujfalusi** [comment]
The debian package is built, but I guess CI cannot find it?
```
dpkg-deb: building package 'linux-image-6.8.0-rc1-g34e36ec622de' in '../linux-image-6.8.0-rc1-g34e36ec622de_6.8.0-rc1-default-pr4793_amd64.deb'.
  INSTALL debian/linux-libc-dev/usr/include
dpkg-deb: building package 'linux-libc-dev' in '../linux-libc-dev_6.8.0-rc1-default-pr4793_amd64.deb'.
dpkg-deb: building package 'linux-headers-6.8.0-rc1-g34e36ec622de' in '../linux-headers-6.8.0-rc1-g34e36ec622de_6.8.0-rc1-default-pr4793_amd64.deb'.
 dpkg-genbuildinfo --build=binary -O../linux-upstream_6.8.0-rc1-default-pr4793_amd64.buildinfo
 dpkg-genchanges --build=binary -O../linux-upstream_6.8.0-rc1-default-pr4793_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build .
dpkg-buildpackage: info: binary-only upload (no source included)
make[1]: Leaving directory '/srv/home/jenkins/workspace/linux_config_build/build/default'
```
@marc-hb, @keqiaozhang, FYI

**Comment by ujfalusi** [comment]
Can this be the reason:
53243e098397 ("kbuild: deb-pkg: remove the fakeroot builds support")
or something else among these?

```
# git log --oneline scripts/package/
6185d32170b6 kbuild: deb-pkg: use debian/<package> for tmpdir
1b5e94657320 kbuild: deb-pkg: move 'make headers' to build-arch
358c3f8cce6d kbuild: deb-pkg: do not search for 'scripts' directory under arch/
16c36f8864e3 kbuild: deb-pkg: use build ID instead of debug link for dbg package
5e73758b43c3 kbuild: deb-pkg: use more debhelper commands in builddeb
68e262f8017d kbuild: deb-pkg: remove unneeded '-f $srctree/Makefile' in debian/rules
eaf80f7f2c9c kbuild: deb-pkg: allow to run debian/rules from output directory
159956f34ede kbuild: deb-pkg: set DEB_* variables if debian/rules is directly executed
7d4f07d5cb71 kbuild: deb-pkg: squash scripts/package/deb-build-option to debian/rules
466e6fc43fb9 kbuild: deb-pkg: factor out common Make options in debian/rules
b88365b6d74e kbuild: deb-pkg: hard-code Build-Depends
9c65810cfb21 kbuild: deb-pkg: split debian/copyright from the mkdebian script
53243e098397 kbuild: deb-pkg: remove the fakeroot builds support
0df8e9708594 scripts: clean up IA-64 code
ef6609adf1ec kbuild: remove the last use of old cmd_src_tar rule in packaging
b28d6ca1c9cb kbuild: buildtar: always make modules_install
884f55f152cb kbuild: buildtar: Remove unused $dirs
```

**Comment by marc-hb** [comment]
I struggled and finally found the complete and very long logs on Jenkins at `job/sofkernel_prs_new/1124`. I unfortunately could not make sense of them. However the kernel build and .deb generation is green there, so I wouldn't waste time in that direction. Maybe some network or server glitch? Can you try an empty `git commit --amend -C HEAD` to change only the SHA1 + force-push?

**Comment by plbossart** [comment]
Not sure what's going on with Jenkins @marc-hb @ujfalusi, the kernel and debian packages seem to build alright but the result in FAIL?

**Comment by keqiaozhang** [comment]
> Not sure what's going on with Jenkins @marc-hb @ujfalusi, the kernel and debian packages seem to build alright but the result in FAIL?

It's because SoCWatch fails to build with 6.8-rc1. 
```
[2024-01-23T08:56:50.303Z] /srv/home/jenkins/workspace/linux_config_build@2/socwatch_build/socwatch/socwatch_driver/./src/sw_output_buffer.c:398:6: error: no previous prototype for ‘reset_output_buffers’ [-Werror=missing-prototypes]
[2024-01-23T08:56:50.303Z]   398 | void reset_output_buffers(void)
[2024-01-23T08:56:50.303Z]       |      ^~~~~~~~~~~~~~~~~~~~
[2024-01-23T08:56:50.640Z] cc1: all warnings being treated as errors
[2024-01-23T08:56:50.640Z] make[3]: *** [/srv/home/jenkins/workspace/linux_config_build@2/linux/scripts/Makefile.build:243: /srv/home/jenkins/workspace/linux_config_build@2/socwatch_build/socwatch/socwatch_driver/./src/sw_output_buffer.o] Error 1
```
I think we may need a new version of SoCWatch packages. I'm working on it.

**Comment by keqiaozhang** [comment]
SOFCI TEST

**Comment by marc-hb** [comment]
> I think we may need a new version of SoCWatch packages. I'm working on it.

This will keep happening because SoCwatch driver are "out of tree" and Linux hates these: https://lwn.net/Articles/860262/ + many  more.

@keqiaozhang can you please:
1. Move the super verbose checkpatch run at the start? The noise stopped us from finding relevant errors in the logs
2. Make SoCwatch compilation OPTIONAL. If SoCwatch fails to compile, then let's ignore that and let the SoCwatch tests fail. We can't have SoCWatch block kernel merges.

An even better solution would be to build SoCWatch as a separate jenkins job that could fail et be reported separately.

**Comment by plbossart** [comment]
> An even better solution would be to build SoCWatch as a separate jenkins job that could fail et be reported separately.

sounds good to me!

**Comment by plbossart** [comment]
https://sof-ci.01.org/linuxpr/PR4793/build1165/devicetest/index.html?model=TGLU_RVP_NOCODEC-ipc4&testcase=check-suspend-resume-with-playback

Is this a known issue @keqiaozhang @ujfalusi  ?

**Comment by ujfalusi** [comment]
@plbossart, I think it was this: https://github.com/thesofproject/sof/issues/8721

**Comment by plbossart** [comment]
@ujfalusi can we merge this? we do need to make progress on upstreaming, we are late already with the 6.8-rc3 to be tagged this Sunday.

**Comment by ujfalusi** [comment]
@plbossart, let's try to merge a new one instead: #4805
